import { readFileSync } from "node:fs";
import path from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { convertPdf, layoutToDmd, readPdf } from "@/src/files/convert/pdf";
import { cleanFontName } from "@/src/files/convert/pdf/pdfjs";
import { ConvertError, DEFAULT_CONVERT_OPTIONS, type ConvertResult } from "@/src/files/convert/types";
import { parseDmd } from "@/src/files/dmd/parse";
import { normalizeDmd } from "@/src/files/dmd/normalize";
import { PAGE_FLAGS, type ParsedDoc } from "@/src/files/dmd/types";

/**
 * pdf.js adapter + layout on real PDFs generated by
 * scripts/make-pdf-fixtures.mjs (pdf-lib, DejaVu Serif with Czech
 * diacritics): pdf.js runs in node with its in-process fake worker. The
 * DMD must round-trip through the strict parser with every footnote bound.
 */

const DIR = path.resolve(import.meta.dirname, "fixtures/files/pdf");

function load(name: string): ArrayBuffer {
  const buf = readFileSync(path.join(DIR, name));
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

async function convert(name: string): Promise<{ result: ConvertResult; parsed: ParsedDoc }> {
  const result = await convertPdf(load(name), DEFAULT_CONVERT_OPTIONS);
  expect(normalizeDmd(result.dmd).changed).toBe(false);
  return { result, parsed: parseDmd(result.dmd) };
}

async function rejection(p: Promise<unknown>): Promise<ConvertError> {
  try {
    await p;
  } catch (e) {
    return e as ConvertError;
  }
  throw new Error("no error");
}

describe("commentary.pdf (running heads, § headings, m. č., footnotes, printed pages)", () => {
  let result: ConvertResult;
  let parsed: ParsedDoc;
  beforeAll(async () => ({ result, parsed } = await convert("commentary.pdf")));

  it("labels the pages with the printed numbers 1245–1248", () => {
    expect(result.labelSource).toBe("printed");
    expect(result.pageLabels).toEqual(["1245", "1246", "1247", "1248"]);
    expect(parsed.pages.map((p) => p.label)).toEqual(["1245", "1246", "1247", "1248"]);
    expect(result.dmd).not.toMatch(/^124[5-8]$/m);
  });

  it("finds the § headings with their bracketed titles and the commentary's internal headings", () => {
    expect(parsed.sections.map((s) => [s.level, s.kind, s.key, s.heading])).toEqual([
      [1, "par", "par:2913", "§ 2913 [Porušení smluvní povinnosti]"],
      [2, "sub", null, "I. Obecně"],
      [2, "sub", null, "II. Předpoklady odpovědnosti"],
      [1, "par", "par:2914", "§ 2914 [Odpovědnost za jiného]"],
      [2, "sub", null, "I. Obecně"],
    ]);
    expect(parsed.problems.filter((p) => p.code === "par_not_monotonic")).toEqual([]);
    // "§ 2910" inside a body line stays text.
    expect(result.dmd).toContain("Na to navazuje § 2910 o odpovědnosti");
  });

  it("sets the statute wording as a quote", () => {
    expect(result.dmd).toContain("> (1) Poruší-li strana povinnost ze smlouvy, nahradí škodu z toho vzniklou druhé straně smlouvy nebo i osobě");
    expect(parsed.blocks.filter((b) => b.kind === "quote")).toHaveLength(2);
  });

  it("prefixes the paragraphs with the marginal numbers, restarting at each §", () => {
    const anchors = parsed.blocks.filter((b) => b.anchor).map((b) => b.anchor);
    expect(anchors).toEqual(["1", "2", "3", "1", "2", "3"]);
    expect(parsed.problems.filter((p) => p.code === "mn_sequence")).toEqual([]);
    expect(result.quality.mn).toBe(6);
  });

  it("binds every footnote, including a note continuing on the next page and a '4)' label", () => {
    expect(parsed.footnotes.map((f) => f.label)).toEqual(["1", "2", "3", "4", "5"]);
    expect(parsed.stats.danglingRefs).toBe(0);
    expect(parsed.stats.danglingDefs).toBe(0);
    const def = (label: string) => {
      const f = parsed.footnotes.find((x) => x.label === label)!;
      return parsed.text.slice(f.defStart, f.defEnd);
    };
    expect(def("2")).toBe("MELZER, F. In: PETROV, J., VÝTISK, M., BERAN, V. a kol. Občanský zákoník. Komentář. 2. vydání. Praha: C. H. Beck, 2019, s. 1245, kde se výklad dále rozvádí i ve vztahu k § 2910.");
    expect(def("4")).toBe("Viz též § 2914 odst. 2 a výklad k § 2915.");
    expect(parsed.footnotes.map((f) => parsed.pages[f.page - 1].label)).toEqual(["1245", "1245", "1246", "1247", "1248"]);
    expect(result.quality).toMatchObject({ footnotes: "linked", linked_ratio: 1 });
  });

  it("joins hyphenated words, keeps the Czech repeated hyphen and joins across the page break", () => {
    expect(result.dmd).toContain("porušení povinnosti předpokladem");
    expect(result.dmd).toContain("starší česko-slovenská judikatura");
    expect(result.dmd).toContain("omezuje rozsah odpovědnosti [s. 1246] na škodu");
  });

  it("keeps running heads, the watermark and rotated text out of the body", () => {
    for (const text of ["Díl 2 ·", "§ 2913 ·", "Díl 3 ·", "§ 2914 ·", "jan.novak", "Zakoupeno", "Licence pro"]) expect(result.dmd).not.toContain(text);
    expect(result.hints.running_heads?.map((h) => h.text)).toEqual([
      "Díl 2 · Následky porušení smluvní povinnosti",
      "§ 2913 · Porušení smluvní povinnosti",
      "Díl 3 · Odpovědnost za jiného",
      "§ 2914 · Odpovědnost za jiného",
    ]);
    expect(JSON.stringify(result.hints)).not.toContain("jan.novak");
  });

  it("reports the PDF info and Czech warnings", () => {
    expect(result.hints.pdf_info).toMatchObject({ title: "Občanský zákoník VI. Závazkové právo. Komentář", author: "Petrov, Výtisk, Beran a kol." });
    expect(result.warnings.some((w) => w.includes("vodoznakem"))).toBe(true);
    expect(result.pageFlags).toEqual([0, 0, 0, 0]);
    expect(result.physicalPages).toBe(4);
  });
});

describe("journal-2col.pdf (two columns, /PageLabels)", () => {
  let result: ConvertResult;
  let parsed: ParsedDoc;
  beforeAll(async () => ({ result, parsed } = await convert("journal-2col.pdf")));

  it("uses the PDF's page labels", () => {
    expect(result.labelSource).toBe("pdf_labels");
    expect(parsed.pages.map((p) => p.label)).toEqual(["417", "418"]);
  });

  it("reads the columns in order and joins the paragraph and split words across them", () => {
    expect(result.pageFlags.every((f) => f & PAGE_FLAGS.COLUMNS)).toBe(true);
    expect(result.quality.columns_pages).toBe(2);
    expect(result.dmd).toContain("nového soukromého práva");
    expect(result.dmd).toContain("východiskem i pro další případy, například pro náhradu duševních útrap");
    expect(result.dmd).toContain("bez zásahu zákonodárce. Kritici namítají");
  });

  it("finds the title, the section headings and binds the notes (the author's asterisk too)", () => {
    expect(parsed.sections.map((s) => s.heading)).toEqual(["Náhrada nemajetkové újmy v judikatuře", "1. Úvod", "2. Újma na zdraví"]);
    expect(parsed.footnotes.map((f) => [f.label, f.refAt !== null])).toEqual([["*", true], ["1", true], ["2", true]]);
    expect(result.dmd).toContain("Jana Nováková[^*]");
    expect(result.hints.running_heads?.map((h) => h.text)).toEqual(["Právní rozhledy 12/2019", "Nováková: Náhrada nemajetkové újmy"]);
  });
});

describe("word-tagged.pdf (tagged, outline, no page numbers)", () => {
  let result: ConvertResult;
  let parsed: ParsedDoc;
  beforeAll(async () => ({ result, parsed } = await convert("word-tagged.pdf")));

  it("takes the headings from the outline, at its levels", () => {
    expect(result.quality.headings_from).toBe("outline");
    expect(parsed.sections.map((s) => [s.level, s.heading])).toEqual([
      [1, "1. Úvod"],
      [1, "2. Právní rozbor"],
      [2, "2.1 Předvídatelnost škody"],
      [1, "3. Závěr"],
    ]);
  });

  it("keeps ragged-right paragraphs whole and binds the footnotes", () => {
    const paras = parsed.blocks.filter((b) => b.kind === "para").map((b) => parsed.text.slice(b.start, b.end));
    expect(paras[0]).toBe(
      "Tento text shrnuje pravidla odpovědnosti za škodu způsobenou porušením smluvní povinnosti podle občanského zákoníku.[^1] Zaměřuje se na předpoklady odpovědnosti a na liberační důvody.",
    );
    expect(paras).toHaveLength(5);
    expect(parsed.footnotes.every((f) => f.refAt !== null)).toBe(true);
    expect(parsed.footnotes).toHaveLength(3);
  });

  it("falls back to physical page numbers and says so", () => {
    expect(result.labelSource).toBe("physical");
    expect(result.pageLabels).toEqual(["1", "2"]);
    expect(result.warnings.some((w) => w.startsWith("Tištěná čísla stran"))).toBe(true);
    expect(result.hints.pdf_info?.producer).toContain("Microsoft");
  });
});

describe("readPdf", () => {
  it("reports progress, keeps the caller's buffer usable and maps real font names and bold", async () => {
    const data = load("commentary.pdf");
    const progress: Array<[number, number]> = [];
    const doc = await readPdf(data, (done, total) => progress.push([done, total]));
    expect(progress).toEqual([[1, 4], [2, 4], [3, 4], [4, 4]]);
    expect(data.byteLength).toBeGreaterThan(0);
    expect(doc.pages).toHaveLength(4);
    expect(doc.pages[0]).toMatchObject({ ord: 1, width: 520, height: 720 });
    const heading = doc.pages[0].items.find((i) => i.str === "§ 2913")!;
    expect(heading).toMatchObject({ bold: true, size: 11 });
    expect(heading.font).toMatch(/^DejaVuSerif-Bold/);
    const body = doc.pages[0].items.find((i) => i.str === "Ustanovení")!;
    expect(body.bold).toBe(false);
    expect(body.y).toBeCloseTo(192, 1);
    expect(doc.pages[0].items.some((i) => i.rotated && i.str.includes("Zakoupeno"))).toBe(true);
    expect(doc.info.Producer).toBe("Adobe PDF Library 17.0");
    expect(doc.ocr).toBe(false);
    expect(doc.pageLabels).toBeNull();
    // Reading the same buffer again works (pdf.js got a copy).
    expect((await readPdf(data)).pages).toHaveLength(4);
  });

  it("resolves the outline to pages and viewport y", async () => {
    const doc = await readPdf(load("word-tagged.pdf"));
    expect(doc.outline.map((e) => [e.title, e.page, e.level])).toEqual([
      ["1. Úvod", 1, 0],
      ["2. Právní rozbor", 1, 0],
      ["2.1 Předvídatelnost škody", 2, 1],
      ["3. Závěr", 2, 0],
    ]);
    expect(doc.outline[0].y).toBeCloseTo(76, 0);
  });

  it("reads /PageLabels", async () => {
    expect((await readPdf(load("journal-2col.pdf"))).pageLabels).toEqual(["417", "418"]);
  });

  it("extracts only the requested page range", async () => {
    const doc = await readPdf(load("commentary.pdf"), undefined, { pageRange: [2, 3] });
    expect(doc.pages.map((p) => p.items.length > 0)).toEqual([false, true, true, false]);
    const result = layoutToDmd(doc, { ...DEFAULT_CONVERT_OPTIONS, pageRange: [2, 3] });
    expect(parseDmd(result.dmd).pages.map((p) => p.label)).toEqual(["1246", "1247"]);
    expect(result.pageLabels).toEqual(["1245", "1246", "1247", "1248"]);
  });

  it("rejects a password-protected PDF", async () => {
    const e = await rejection(readPdf(load("encrypted.pdf")));
    expect(e).toBeInstanceOf(ConvertError);
    expect(e.code).toBe("encrypted");
    expect(e.message).toContain("heslem");
  });

  it("rejects bytes that are not a PDF", async () => {
    const e = await rejection(readPdf(new TextEncoder().encode("toto není PDF, jen text").buffer as ArrayBuffer));
    expect(e).toBeInstanceOf(ConvertError);
    expect(e.code).toBe("broken");
  });

  it("rejects a scan without a text layer (convertPdf)", async () => {
    const e = await rejection(convertPdf(load("scan.pdf"), DEFAULT_CONVERT_OPTIONS));
    expect(e).toBeInstanceOf(ConvertError);
    expect(e.code).toBe("scan");
  });

  it("marks a scanner / OCR producer as an OCR layer", async () => {
    const doc = await readPdf(load("scan.pdf"));
    expect(doc.ocr).toBe(true);
  });
});

describe("cleanFontName", () => {
  it("drops the subset prefix", () => {
    expect(cleanFontName("ABCDEF+Minion-Bold")).toBe("Minion-Bold");
    expect(cleanFontName("Minion-Bold")).toBe("Minion-Bold");
    expect(cleanFontName("abcdef+X")).toBe("abcdef+X");
    expect(cleanFontName("")).toBe("");
  });
});
